version: dev.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild Vic2ToHoI4.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild Vic2ToHoI4Tests/Vic2ToHoI4Tests-Google.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
- ps: >-
    vstest.console /logger:Appveyor frontend\Frontend.Core.Tests\bin\Release\Frontend.Core.Tests.dll

    cd Release\Vic2ToHoI4

    ..\..\Vic2ToHoI4Tests\Release\Vic2ToHoI4Tests.exe --gtest_output=xml:tests.xml

    (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
artifacts:
- path: Release
  name: Vic2ToHoI4
deploy:
- provider: GitHub
  release: windows_development_build
  description: The most recent build of the development version
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: idhrendur/Vic2ToHoI4
  artifact: Vic2ToHoI4
  prerelease: true
  force_update: true